language: python
python:
  - "2.7"

install:
  - "pip install pytest"
  - "python setup.py develop"

script: py.test

sudo: false

env:
  global:
  - BUCKET=presslabstest
  - secure: kbs108vBEMhBSlZfMhLriILqf5+llznVIogucmUfGw9un2zmHSvN3xWEgRVOprVUjf7yeg8sW2XAtjX2XAhMQEDFLksET00U6m3BhqvyJv2SKXGi+yeUhKuGD/TgmV7gHK4wEBUnKrgDzrjGTTCU6DdXAEhs/iBrfzkhlTA8PNWyyI5yiu4LlciAxQiWRJuFavWMEwTf9pxNseTfVXtG0aO5SeeyDHyT4s2CVsjSb2DtY6A7dEZEhUFc2Qt29WuiYtg/PHFWD585szHtXdHKCxwbOLAYUZSrLN3HafdkZtaS0bWEi3Epl6jy1POO2h8nTKZ/9FCkhB1p9tZjn3OIYuCCQFvpONxHyldnKaGwitWB8/PBiME+a/0CfK8KQHDpL3c7jjkW0TwH8PpmMftwkR5MwvbnfKGvy2vVouXX8k6pTebFgszp49SQuNMp2xrupFOO96v3B28DN+yYyg0htFFkRdOd7doxcnaulZMoQC8cCtt+wpuWdz/CW6H3iqv76MKohcjhhP+3BovImU3D2HenGP2F/V+3nY8zIxa8M5r2THsKG4wko2hJT2hKjNyUtMr5WxMwEMSPDFJfSqskHl+0OHnmSWMQ6gTtcnIuhOJ2Jb+ZwiWjhsn2Hq/bgfnAhgAs+9vgeVVROB/V7XakeAWIUlRRIQ030NPaaWwysrQ=
  - secure: ZY4pqYBa9kdUOk22mBzQ338gxjqKCCipubg20teC/z0zDoqlLcL0+AS8vKlGVTH2GW9jWSP6OIuluf0/w0YG/pNZ1FiSLvKlmZTd6Ba/uWbu2pN+I34PO1em/Ymo1ZkAXEaorQCoO1ZQpKLFVi1VUH7S9ba1H6itsyF5lVCCtIM4Ot5snaBhyrlww0ZmBN8CD3FCV/rLlJzhwc98BGe9cNB5oX8KvQcn+GkvVUAR79awLNkhTElQB2jqaYTwq63807C2NcxOoJK1zlHNQM6XmgDiDWL/xS0Je99on1Mazd6sBec+IPREBRmlmJ+/g+LmjI/CCxKdxWjC8atk/x9Xg1KEyQO6hrSWLNuL2pWKA72jJCsZpjB8MU4+LAEiLUSMOOTXU451P24b/8TU2e5Z49ju23MbUgQWqAaIvkAFfd3Ni0iuF6Iu287Hg99g5FxcKTcfgetc5x9SUlUx1RRu9K6K7ztJ7fjIfi5Zv9hJ0Sen04pJkZz+xoSeS9EZHQwNX+OmWP2u6L1Kn1tXg3GPLz1NGIY/Jd/zXrwveQpSfLqGKQpwMf4Sj44u/P0zPMOPVju+7nc3xlHknDaKT23VJmTo7PTk25rH9SF/hEAJnODVCvq1krbhN3oFSPLt/6bUHErEi5ugQ6DBm20temvm6Ci9dJOso1Pg7CysSfuNieE=
